### ISSUE TITLE
Cannot access to the supplementary material of the paper

### ISSUE THREAD

**Issue by ita9naiwa** [lwangbm/Metis#1]
first of all, thanks for your nice work!
I am currently reading your work, but I can't have access to the supplementary materials (https://bit.ly/3blZMgc)

How can I get this...?

**Comment by lwangbm** [comment]
Thank you for ur interest. In our final version, we have included almost all the content in our main paper, which can be found here https://www.cse.ust.hk/~weiwa/papers/metis-sc20.pdf.
And the appendix u mention here has been removed.

**Comment by ita9naiwa** [comment]
Okay. Thanks for your kind help!
